### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#18]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by mdangschat** [comment]
I second that.

**Comment by EddyVerbruggen** [comment]
OK, it's [up there](https://www.npmjs.com/package/cordova-plugin-insomnia) now :)

**Comment by bau720123** [comment]
thanks @EddyVerbruggen
