### ISSUE TITLE
cordova is not defined

### ISSUE THREAD

**Issue by DeanWilliamMills** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#24]
Hi Eddy

Can you please help me. I get the following error when I add Insomnia in my project:

Uncaught ReferenceError: cordova is not defined
(anonymous function) @ Insomnia.js:21

It is this line : cordova.addConstructor(Insomnia.install);

Your help will be appreciated.

**Comment by mouthzipper** [comment]
make sure to add cordova.js in your index.html before calling insomnia.js
<script src="cordova.js"></script>
<script src="Insomnia.js"></script>

**Comment by safanmomin** [comment]
Not necessary to include the inomnia.js file just include the cordova.js file and you're good to go! :)
