### ISSUE TITLE
How to auto keepAwake on launch of the app

### ISSUE THREAD

**Issue by mirzabros** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#25]
Hi there.

I have a switch ON OFF to keep screen awake. This is working file but I want to enable keepAwake from the time it starts the app. 

Please help me out with this.

I am happy to pay for time. 

Thanks

**Comment by purplecabbage** [comment]
```
document.addEventListener("deviceready",function() {
    window.plugins.insomnia.keepAwake();
});
```

**Comment by dragonprojects** [comment]
Hi,
I try the same: enable keepAwake on the app start.
Can you pls have a quick look into it if its a problem on my side or the plugin:

- my config.xml: https://github.com/dscores/dqwixx-phonegap/blob/master/config.xml#L5
- the index.html which include the scorecard-phonegap.js: https://github.com/dscores/dqwixx-phonegap/blob/master/www/index.html#L24
- the few lines from the comment here: https://github.com/dscores/dqwixx-phonegap/blob/master/www/scorecard-phonegap.js

The app build can be found here: https://build.phonegap.com/apps/1944299/share

**Comment by EddyVerbruggen** [comment]
@dragonprojects you're not including a reference to `cordova.js` in `index.html`. And you may want to consider using the plugin from npm instead of the old one on pgb: `<plugin name="cordova-plugin-insomnia" source="npm" />`

**Comment by dragonprojects** [comment]
Thx, will try it.

little bit off topic: you know a good way to add the script tags into the index.html for some build specific javascripts (cordova.js and in my case the scorecard-phonegap.js) during the phonegap build?
So the normal webpage doesn't need to link them.

**Comment by EddyVerbruggen** [comment]
Google my friend, Google.
And if that fails: StackOverflow.
