### ISSUE TITLE
reference npm package in README

### ISSUE THREAD

**Issue by Ruff9** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#31]
I had to browse issues to find out there was an NPM package for the plugin.

https://www.npmjs.com/package/cordova-plugin-insomnia

A README update would be nice :)

**Comment by EddyVerbruggen** [comment]
Indeed. Can you send a PR?

**Comment by Ruff9** [comment]
done :)

**Comment by EddyVerbruggen** [comment]
Cool, thanks! 👍
