### ISSUE TITLE
error installing plugin on ionic 3 project

### ISSUE THREAD

**Issue by flyingwip** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#39]
When trying to install plugin in Ionic 3 plugin I get 

ionic cordova plugin add https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git :

✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.gi... (exit code 1):

        Error: Failed to fetch plugin https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: not found: git
        npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
        npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
        npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
        npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
        npm WARN addRemoteGit  git+https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git resetting remote C:\Users\[user]\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Insomnia-PhoneGap-Plugin-git-223bcd2c because of error: { Error: not found: git
        npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
        npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
        npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
        npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
        npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
        npm ERR! git clone --template=C:\Users\[user]\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git C:\Users\[user]\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Insomnia-PhoneGap-Plugin-git-223bcd2c: undefined
        npm ERR! git clone --template=C:\Users\[user]\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git C:\Users\[user]\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-EddyVerbruggen-Insomnia-PhoneGap-Plugin-git-223bcd2c: undefined
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git" "--save"
        npm ERR! node v6.9.4
        npm ERR! npm  v3.10.10
        npm ERR! code ENOGIT

        npm ERR! not found: git
        npm ERR!
        npm ERR! Failed using git.
        npm ERR! This is most likely not a problem with npm itself.
        npm ERR! Please check if you have git installed and in your PATH.

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\[user]\Documents\GGD-Projects\tint\tint\node_modules\npm-debug.log

**Comment by EddyVerbruggen** [comment]
` npm ERR! Please check if you have git installed and in your PATH.` <-- does that help?

**Comment by flyingwip** [comment]
ah I see now i forgot to reply. It did work. Thank you for responding.
