### ISSUE TITLE
Error on Cordova Install

### ISSUE THREAD

**Issue by camilacanhete** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#40]
Error: Failed to fetch plugin git+https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

**Comment by EddyVerbruggen** [comment]
Try installing `cordova-plugin-insomnia` from npm instead.
