### ISSUE TITLE
Working fine in android but not in IOS

### ISSUE THREAD

**Issue by deligence** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#45]
Hello

We have a app which uses BLE device to communicate, We are tracking stats of this BLE device and showing in our mobile devices, everything seems to be working fine except one thing, which is when we stop our BLE device it should not increment timer in our application, but it is not working in IOS, but working fine in android, But the main issue is that it is occurring only when our application is running in background or when the mobile screen is shut off(working fine in foreground), we have research but not found anything related to my requirement.

I am using iPhone 6s with IOS 11 and I am creating application in meteor 1.3.

Can you please help me out with this issue?

Thanks

**Comment by EddyVerbruggen** [comment]
This plugin only works in the foreground; it prevents the screen from dimming and (eventually) locking the device. Is that what you expect as well?

**Comment by deligence** [comment]
Thanks @EddyVerbruggen for so much quick response, you mean to say it will work only when the application is in the foreground and not work when the application is in the background( or when the mobile screen is off), right?

**Comment by EddyVerbruggen** [comment]
Yes

**Comment by deligence** [comment]
Thanks a lot
