### ISSUE TITLE
Unable to submit app to App Store

### ISSUE THREAD

**Issue by bushev** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#57]
ITMS-90338: Non-public API usage - The app references non-public selectors in ***: **_setAlwaysRunsAtForegroundPriority**:, zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:unzippedFilePath:, zipArchiveProgressEvent:total:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by EddyVerbruggen** [comment]
Looking at the [source code](https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin/blob/master/src/ios/Insomnia.m) this plugin doesn't use private API's.
