### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'window.plugins.insomnia')

### ISSUE THREAD

**Issue by kalepail** [EddyVerbruggen/Insomnia-PhoneGap-Plugin#7]
Hey, loving this little plugin, but ran into a bug when in development. It's working like a charm once you're on the phone but is throwing an error when building in development on a non phone server.

It's throwing the `TypeError: 'undefined' is not an object (evaluating 'window.plugins.insomnia')` I assume this has something to do with newer versions of Cordova not building out the JS or something. Any ideas for a fix or work around so I can get back to developing without having to comment this line out all the time?

**Comment by awuge** [comment]
undefined is not an object (evaluating 'window.plugins.oaCommonOperate.finish')， undefined is not an object (evaluating 'window.plugins.oaCommonOperate.finish')！How did you solve it？

**Comment by awuge** [comment]
The custom plug-in cordova is wrong， undefined is not an object (evaluating 'window.plugins.oaCommonOperate.finish')！How did you solve it？
